### ISSUE TITLE
WCMS-3056-1: Create a new table of contents for the repository

### ISSUE THREAD

**Issue by mthpvg** [upfrontIO/livingdocs#35]
### Prerequisites
- List documents from this repository plus those scattered on the other repositories (upfrontio and nzzdev)
- Assess the quality/relevance of each documents
- Classify those documents according to the taxonomy

### Deliverables
A document that holds a new table of contents for this repository

**Comment by masone** [comment]
moved to https://github.com/upfrontIO/livingdocs-planning/issues/14
