### ISSUE TITLE
WCMS-3056-0: Create a documentation taxonomy

### ISSUE THREAD

**Issue by mthpvg** [upfrontIO/livingdocs#36]
The documentation taxonomy is a short document describing the classification for the Livingdocs documentation.

Examples of concepts to classify:
- API documentation
- Livingdocs architecture
- Hardware requirements
- Migration cheatsheet
- ...

### Deliverables
A document describing the taxonomy

**Comment by masone** [comment]
Please provide a draft in google drive. Once approved, we should move it to the guides repo.

**Comment by mthpvg** [comment]
Here is the draft on Google Drive:
https://docs.google.com/document/d/1fr6LZH16a53qdFzAi05oC8nqMYzG4v6BWgTdtOmIaxE/edit

**Comment by masone** [comment]
moved to https://github.com/upfrontIO/livingdocs-planning/issues/11
