### ISSUE TITLE
WCMS-3056-2: Describe the layout and content of a readme

### ISSUE THREAD

**Issue by mthpvg** [upfrontIO/livingdocs#37]
### Prerequisites
- Go through all the readmes from upfrontio and nzzdev and sort what they contain
- Remove informations that belong to the central repository (livingdocs repository) according to the taxonomy
- Remove informations that belong to the guides again according to the taxonomy
- It should only holds instructions

### Deliverables
Document that describe the layout and the content of a readme

**Comment by masone** [comment]
moved to https://github.com/upfrontIO/livingdocs-planning/issues/12
