### ISSUE TITLE
The Server API documentation is missing

### ISSUE THREAD

**Issue by groie** [upfrontIO/livingdocs#6]
The frontpage of Livingdocs documentation (https://github.com/upfrontIO/livingdocs) has a link to the Server API. This link gives me 404.

**Comment by peyerluk** [comment]
Thanks for the comment. The server is a closed source project and we have to move the documentation out of there.

**Comment by groie** [comment]
Thanks!  :+1: Looking forward!

**Comment by marcbachmann** [comment]
Will close this because we've moved the documentation into this repo. Here's the link: https://github.com/upfrontIO/livingdocs/blob/master/server/home.md
